# Generated by Django 5.2.14 on 2026-05-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('authors', models.CharField(blank=True, default='', max_length=500, verbose_name='作者')),
                ('doi', models.CharField(blank=True, default='', max_length=200, verbose_name='DOI')),
                ('url', models.URLField(blank=True, default='', verbose_name='链接')),
                ('venue', models.CharField(blank=True, default='', max_length=200, verbose_name='发表于')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('takeaway', models.TextField(blank=True, default='', verbose_name='核心贡献')),
                ('notes', models.TextField(blank=True, default='', verbose_name='详细笔记 (Markdown)')),
                ('status', models.CharField(choices=[('unread', '待读'), ('reading', '在读'), ('finished', '已读'), ('archived', '归档')], default='unread', max_length=20, verbose_name='状态')),
                ('tags', models.CharField(blank=True, default='', help_text='逗号分隔，如：RAG,LLM,Agent', max_length=500, verbose_name='标签')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='评分 (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '论文',
                'verbose_name_plural': '论文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='实验名称')),
                ('model_name', models.CharField(blank=True, default='', max_length=200, verbose_name='模型/方法')),
                ('params', models.TextField(blank=True, default='', help_text='如 lr=0.001, batch=32, epochs=100', verbose_name='参数配置')),
                ('metrics', models.TextField(blank=True, default='', help_text='如 Accuracy=0.95, F1=0.92', verbose_name='指标结果')),
                ('dataset', models.CharField(blank=True, default='', max_length=200, verbose_name='数据集')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('gpu_hours', models.FloatField(blank=True, null=True, verbose_name='GPU 小时')),
                ('checkpoint', models.CharField(blank=True, default='', max_length=500, verbose_name='权重路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='research.paper', verbose_name='关联论文')),
            ],
            options={
                'verbose_name': '实验',
                'verbose_name_plural': '实验',
                'ordering': ['-created_at'],
            },
        ),
    ]
