# Generated by Django 5.2.14 on 2026-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='内容')),
                ('icon', models.CharField(default='📌', max_length=4, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '当前在做',
                'verbose_name_plural': '当前在做',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': '里程碑', 'verbose_name_plural': '里程碑'},
        ),
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.CharField(default='📌', max_length=4, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
    ]
