# Generated by Django 5.2.14 on 2026-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_date', models.DateField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('lead', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('item_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=1024)),
                ('body', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=32)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('score', models.IntegerField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('summary_short', models.TextField(blank=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='PullCursor',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
