# Generated by Django 5.2.14 on 2026-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('icon', models.CharField(blank=True, help_text='图标类名或emoji', max_length=50, verbose_name='图标')),
                ('category', models.CharField(choices=[('service', '服务器服务'), ('external', '外部链接'), ('project', '个人项目')], default='external', max_length=20, verbose_name='分类')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
