# Generated by Django 5.2.17 on 2026-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon_file',
            field=models.CharField(blank=True, default='', help_text='放在 static/icons/links/ 下的文件名，如 github.svg；优先于 emoji', max_length=120, verbose_name='本地图标文件'),
        ),
    ]
